title: Henry
description: My Personal Blog
author: Henry Fung
logo: /blog/static/img/avatar.png
github: https://github.com/henryfung3a27
about: Happy developer

baseurl: "/blog"
url: ""

allowsearch: true

disqus_shortname: henryfung3a27
google_analytics: UA-141054935-1

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
